require("dotenv").config()
const express =  require("express")
const connectDB = require("./config/db")
const userAPI = require("./API/userAPI")
const requestAPI = require("./API/requestAPI")
const shiftAPI = require("./API/shiftAPI")
const shiftRequestAPI = require("./API/shiftRequestAPI")
const assignmentAPI = require("./API/assignmentAPI")
const app  = express()
app.use(express.json()) 
connectDB()
app.use("/users",userAPI)
app.use("/requests",requestAPI)
app.use("/shifts", shiftAPI)
app.use("/shift-requests", shiftRequestAPI)
app.use("/assignments", assignmentAPI)
app.listen(process.env.PORT, () => {
    console.log(`Server is running on port ${process.env.PORT}`)
})